# Generated by Django 3.1.1 on 2020-09-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_userlevel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newenduser',
            name='name',
        ),
        migrations.AddField(
            model_name='newenduser',
            name='first_name',
            field=models.CharField(default='Jason', max_length=50),
        ),
        migrations.AddField(
            model_name='newenduser',
            name='last_name',
            field=models.CharField(default='Villa', max_length=50),
        ),
        migrations.AddField(
            model_name='newenduser',
            name='middle_i',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
