# Generated by Django 3.1.1 on 2020-09-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20200929_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newenduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newenduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='newenduser',
            name='middle_i',
        ),
        migrations.AddField(
            model_name='newenduser',
            name='name',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
