# Generated by Django 3.1.1 on 2020-10-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20200929_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='acc_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='newapp.accountcode'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='newapp.article'),
        ),
    ]
