# Generated by Django 3.1.1 on 2020-10-19 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_receipt_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='amounts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_received_by_bac',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_received_by_supplier',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='fund_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='newapp.fundsource'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='mode_of_procurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='newapp.modeofprocurement'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='requesting_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='newapp.requestingenduser'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='newapp.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='term_of_delivery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
