# Generated by Django 3.1.1 on 2020-10-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20201020_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='with_acc_codes',
            field=models.BooleanField(default=False),
        ),
    ]
