# Generated by Django 3.1.1 on 2020-10-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_inspection_with_acc_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymonitoring',
            name='equipment_status',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymonitoring',
            name='wmr',
            field=models.CharField(default='a', max_length=15),
            preserve_default=False,
        ),
    ]
