# Generated by Django 3.1.1 on 2020-10-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_newenduser_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymonitoring',
            old_name='date_transfered',
            new_name='date_transferred',
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='wmr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
