# Generated by Django 3.1.1 on 2020-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_auto_20201028_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymonitoring',
            name='overage',
        ),
        migrations.AddField(
            model_name='inventorymonitoring',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventorymonitoring',
            name='purpose',
            field=models.TextField(null=True),
        ),
    ]
