# Generated by Django 3.1.1 on 2020-10-31 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_justdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JustDate',
        ),
        migrations.AddField(
            model_name='inventorymonitoring',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inventorymonitoring',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='qr_codes'),
        ),
    ]
