# Generated by Django 3.1.1 on 2020-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_auto_20201031_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='qr_codes'),
        ),
    ]
