# Generated by Django 3.1.1 on 2020-11-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_auto_20201106_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymonitoring',
            name='img',
        ),
    ]
