# Generated by Django 3.1.1 on 2020-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_remove_inventorymonitoring_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymonitoring',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='qr_codes'),
        ),
    ]
