# Generated by Django 3.1.1 on 2020-11-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_auto_20201110_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='date_received_by_bac',
            new_name='date_received_from_bac',
        ),
        migrations.RemoveField(
            model_name='inventorymonitoring',
            name='img',
        ),
    ]
