# Generated by Django 3.1.1 on 2020-11-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_auto_20201116_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='equipment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='wmr',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='newenduser',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
