# Generated by Django 3.1.1 on 2020-11-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_auto_20201117_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='scans')),
            ],
        ),
    ]
