# Generated by Django 3.1.1 on 2021-02-07 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0023_scanmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='accountcode',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='inspection',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.campus'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.inspectionofficer'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='receive_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.receivestatus'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='requisitioning_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.requisitioningoffice'),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.item'),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='remarks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.itemuser'),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='transferred_to_new_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.newenduser'),
        ),
        migrations.AlterField(
            model_name='item',
            name='acc_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.accountcode'),
        ),
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.article'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.inspection'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.unit'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='fund_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.fundsource'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='mode_of_procurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.modeofprocurement'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='requesting_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.requestingenduser'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.supplier'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.inspection'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.receipttype'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.level'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
