# Generated by Django 3.1.1 on 2021-02-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_item_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='classification',
        ),
    ]
