# Generated by Django 3.1.1 on 2021-02-07 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_remove_item_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.classification'),
            preserve_default=False,
        ),
    ]
