# Generated by Django 3.1.1 on 2021-02-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_item_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.item')),
                ('item_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.itemuser')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.purchaseorder')),
            ],
        ),
    ]
