# Generated by Django 3.1.1 on 2021-02-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0028_pars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pars',
            name='item',
        ),
    ]
