# Generated by Django 3.1.1 on 2021-02-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0031_auto_20210222_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymonitoring',
            name='equipment_status',
        ),
        migrations.RemoveField(
            model_name='newenduser',
            name='name',
        ),
        migrations.AddField(
            model_name='newenduser',
            name='equipment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newenduser',
            name='new_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newapp.itemuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newenduser',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.newenduser'),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='shortage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
