# Generated by Django 3.1.1 on 2021-02-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0032_auto_20210301_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newenduser',
            name='transaction_id',
        ),
    ]
