# Generated by Django 3.1.1 on 2021-02-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0033_remove_newenduser_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newenduser',
            name='transaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.newenduser'),
        ),
    ]
