# Generated by Django 3.1.1 on 2021-03-02 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0035_newenduser_from_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('item_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.itemuser')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.purchaseorder')),
            ],
        ),
        migrations.AlterField(
            model_name='newenduser',
            name='from_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.parnumber'),
        ),
        migrations.DeleteModel(
            name='PARs',
        ),
    ]
