# Generated by Django 3.1.1 on 2021-03-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0037_inventorymonitoring_par_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newenduser',
            name='new_user',
        ),
        migrations.AddField(
            model_name='newenduser',
            name='to_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_par', to='newapp.parnumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newenduser',
            name='from_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_par', to='newapp.parnumber'),
        ),
    ]
