# Generated by Django 3.1.1 on 2021-03-21 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0038_auto_20210312_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newenduser',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='parnumber',
            name='date_recorded',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
