# Generated by Django 3.1.1 on 2021-03-26 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0039_auto_20210321_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parnumber',
            name='po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.purchaseorder'),
        ),
    ]
