# Generated by Django 3.1.1 on 2021-03-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0040_auto_20210326_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymonitoring',
            name='transferred_to_new_user',
        ),
    ]
