# Generated by Django 3.1.1 on 2021-03-29 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0042_auto_20210326_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymonitoring',
            name='from_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_par', to='newapp.parnumber'),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='par_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='par_num', to='newapp.parnumber'),
        ),
    ]
