# Generated by Django 3.1.1 on 2021-04-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0043_auto_20210329_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymonitoring',
            name='user_campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.campus'),
        ),
    ]
