# Generated by Django 3.1.1 on 2021-05-23 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0044_inventorymonitoring_user_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='user_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.campus'),
        ),
    ]
