# Generated by Django 3.1.1 on 2021-06-23 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0045_auto_20210524_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inspection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.inspection'),
        ),
    ]
