# Generated by Django 3.1.1 on 2021-06-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0046_auto_20210623_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='series',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
