# Generated by Django 3.1.1 on 2021-06-24 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0047_auto_20210623_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
