# Generated by Django 3.1.1 on 2021-07-13 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0048_inspection_inspection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='po_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
