# Generated by Django 3.1.1 on 2021-07-14 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0049_auto_20210714_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymonitoring',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='po_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
